### ISSUE TITLE
Create a package to manage settings

### ISSUE THREAD

**Issue by kohdice** [kohdice/poke-graphql#1]
## Summary

Create a package to manage settings.

## Purpose

Create a package to centrally manage settings.

## Tasks

- [x] Create a struct to hold configuration information
- [x] Create a function to retrieve the struct holding configuration information
- [x] Create methods to retrieve fields of the struct
